// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/clientrpc/v1/clientrpc.proto

package clientrpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionKind int32

const (
	ActionKind_ACTION_KIND_FOLD  ActionKind = 0
	ActionKind_ACTION_KIND_CHECK ActionKind = 1
	ActionKind_ACTION_KIND_CALL  ActionKind = 2
	ActionKind_ACTION_KIND_RAISE ActionKind = 3
)

// Enum value maps for ActionKind.
var (
	ActionKind_name = map[int32]string{
		0: "ACTION_KIND_FOLD",
		1: "ACTION_KIND_CHECK",
		2: "ACTION_KIND_CALL",
		3: "ACTION_KIND_RAISE",
	}
	ActionKind_value = map[string]int32{
		"ACTION_KIND_FOLD":  0,
		"ACTION_KIND_CHECK": 1,
		"ACTION_KIND_CALL":  2,
		"ACTION_KIND_RAISE": 3,
	}
)

func (x ActionKind) Enum() *ActionKind {
	p := new(ActionKind)
	*p = x
	return p
}

func (x ActionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_clientrpc_v1_clientrpc_proto_enumTypes[0].Descriptor()
}

func (ActionKind) Type() protoreflect.EnumType {
	return &file_proto_clientrpc_v1_clientrpc_proto_enumTypes[0]
}

func (x ActionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionKind.Descriptor instead.
func (ActionKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{0}
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type JoinSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinSessionRequest) Reset() {
	*x = JoinSessionRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSessionRequest) ProtoMessage() {}

func (x *JoinSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSessionRequest.ProtoReflect.Descriptor instead.
func (*JoinSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{2}
}

func (x *JoinSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type JoinSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinSessionResponse) Reset() {
	*x = JoinSessionResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSessionResponse) ProtoMessage() {}

func (x *JoinSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSessionResponse.ProtoReflect.Descriptor instead.
func (*JoinSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{3}
}

func (x *JoinSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersRequest) Reset() {
	*x = ListPeersRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersRequest) ProtoMessage() {}

func (x *ListPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersRequest.ProtoReflect.Descriptor instead.
func (*ListPeersRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{4}
}

type ListPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersResponse) Reset() {
	*x = ListPeersResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersResponse) ProtoMessage() {}

func (x *ListPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersResponse.ProtoReflect.Descriptor instead.
func (*ListPeersResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{5}
}

func (x *ListPeersResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{6}
}

func (x *PeerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PeerInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type ConnectPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectPeersRequest) Reset() {
	*x = ConnectPeersRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectPeersRequest) ProtoMessage() {}

func (x *ConnectPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectPeersRequest.ProtoReflect.Descriptor instead.
func (*ConnectPeersRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{7}
}

type ConnectPeersResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConnectedCount int32                  `protobuf:"varint,1,opt,name=connected_count,json=connectedCount,proto3" json:"connected_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectPeersResponse) Reset() {
	*x = ConnectPeersResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectPeersResponse) ProtoMessage() {}

func (x *ConnectPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectPeersResponse.ProtoReflect.Descriptor instead.
func (*ConnectPeersResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{8}
}

func (x *ConnectPeersResponse) GetConnectedCount() int32 {
	if x != nil {
		return x.ConnectedCount
	}
	return 0
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{9}
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionIds    []string               `protobuf:"bytes,1,rep,name=session_ids,json=sessionIds,proto3" json:"session_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{10}
}

func (x *ListSessionsResponse) GetSessionIds() []string {
	if x != nil {
		return x.SessionIds
	}
	return nil
}

type StartGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameRequest) Reset() {
	*x = StartGameRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequest) ProtoMessage() {}

func (x *StartGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequest.ProtoReflect.Descriptor instead.
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{11}
}

type StartGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameResponse) Reset() {
	*x = StartGameResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameResponse) ProtoMessage() {}

func (x *StartGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameResponse.ProtoReflect.Descriptor instead.
func (*StartGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{12}
}

type SubmitActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ActionKind             `protobuf:"varint,1,opt,name=kind,proto3,enum=clientrpc.v1.ActionKind" json:"kind,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` // only meaningful for RAISE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitActionRequest) Reset() {
	*x = SubmitActionRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitActionRequest) ProtoMessage() {}

func (x *SubmitActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitActionRequest.ProtoReflect.Descriptor instead.
func (*SubmitActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{13}
}

func (x *SubmitActionRequest) GetKind() ActionKind {
	if x != nil {
		return x.Kind
	}
	return ActionKind_ACTION_KIND_FOLD
}

func (x *SubmitActionRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type SubmitActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitActionResponse) Reset() {
	*x = SubmitActionResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitActionResponse) ProtoMessage() {}

func (x *SubmitActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitActionResponse.ProtoReflect.Descriptor instead.
func (*SubmitActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{14}
}

type GetCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsRequest) Reset() {
	*x = GetCardsRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsRequest) ProtoMessage() {}

func (x *GetCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsRequest.ProtoReflect.Descriptor instead.
func (*GetCardsRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{15}
}

type GetCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hand          []string               `protobuf:"bytes,1,rep,name=hand,proto3" json:"hand,omitempty"`
	Flop          []string               `protobuf:"bytes,2,rep,name=flop,proto3" json:"flop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsResponse) Reset() {
	*x = GetCardsResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsResponse) ProtoMessage() {}

func (x *GetCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsResponse.ProtoReflect.Descriptor instead.
func (*GetCardsResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{16}
}

func (x *GetCardsResponse) GetHand() []string {
	if x != nil {
		return x.Hand
	}
	return nil
}

func (x *GetCardsResponse) GetFlop() []string {
	if x != nil {
		return x.Flop
	}
	return nil
}

// CardInfo is the decoded form of one deck-int.
//
//	suit: 0=Clubs, 1=Diamonds, 2=Hearts, 3=Spades
//	rank: 0=Two, 1=Three, ..., 8=Ten, 9=Jack, 10=Queen, 11=King, 12=Ace
type CardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // 0..51
	Suit          int32                  `protobuf:"varint,2,opt,name=suit,proto3" json:"suit,omitempty"`
	Rank          int32                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	Short         string                 `protobuf:"bytes,4,opt,name=short,proto3" json:"short,omitempty"`                       // "AS"
	Pretty        string                 `protobuf:"bytes,5,opt,name=pretty,proto3" json:"pretty,omitempty"`                     // "A\u2660"
	SuitName      string                 `protobuf:"bytes,6,opt,name=suit_name,json=suitName,proto3" json:"suit_name,omitempty"` // "Spades"
	RankName      string                 `protobuf:"bytes,7,opt,name=rank_name,json=rankName,proto3" json:"rank_name,omitempty"` // "Ace"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardInfo) Reset() {
	*x = CardInfo{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardInfo) ProtoMessage() {}

func (x *CardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardInfo.ProtoReflect.Descriptor instead.
func (*CardInfo) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{17}
}

func (x *CardInfo) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *CardInfo) GetSuit() int32 {
	if x != nil {
		return x.Suit
	}
	return 0
}

func (x *CardInfo) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *CardInfo) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *CardInfo) GetPretty() string {
	if x != nil {
		return x.Pretty
	}
	return ""
}

func (x *CardInfo) GetSuitName() string {
	if x != nil {
		return x.SuitName
	}
	return ""
}

func (x *CardInfo) GetRankName() string {
	if x != nil {
		return x.RankName
	}
	return ""
}

type DescribeCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []string               `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"` // deck-int strings (e.g. "0", "33")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeCardsRequest) Reset() {
	*x = DescribeCardsRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeCardsRequest) ProtoMessage() {}

func (x *DescribeCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeCardsRequest.ProtoReflect.Descriptor instead.
func (*DescribeCardsRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{18}
}

func (x *DescribeCardsRequest) GetCards() []string {
	if x != nil {
		return x.Cards
	}
	return nil
}

type DescribeCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*CardInfo            `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeCardsResponse) Reset() {
	*x = DescribeCardsResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeCardsResponse) ProtoMessage() {}

func (x *DescribeCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeCardsResponse.ProtoReflect.Descriptor instead.
func (*DescribeCardsResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{19}
}

func (x *DescribeCardsResponse) GetCards() []*CardInfo {
	if x != nil {
		return x.Cards
	}
	return nil
}

// EvaluateHand ranks the strongest 5-card hand from 5..7 deck-int cards.
type EvaluateHandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []string               `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"` // 5..7 deck-int strings
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateHandRequest) Reset() {
	*x = EvaluateHandRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateHandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateHandRequest) ProtoMessage() {}

func (x *EvaluateHandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateHandRequest.ProtoReflect.Descriptor instead.
func (*EvaluateHandRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{20}
}

func (x *EvaluateHandRequest) GetCards() []string {
	if x != nil {
		return x.Cards
	}
	return nil
}

type EvaluateHandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// category: 0=HighCard, 1=Pair, 2=TwoPair, 3=Trips, 4=Straight,
	//
	//	5=Flush, 6=FullHouse, 7=Quads, 8=StraightFlush
	Category      int32       `protobuf:"varint,1,opt,name=category,proto3" json:"category,omitempty"`
	CategoryName  string      `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"` // "Full House"
	Description   string      `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                       // "Full House, Aces full of Kings"
	Tiebreakers   []int32     `protobuf:"varint,4,rep,packed,name=tiebreakers,proto3" json:"tiebreakers,omitempty"`               // most-significant first
	Best          []*CardInfo `protobuf:"bytes,5,rep,name=best,proto3" json:"best,omitempty"`                                     // the 5 selected cards in display order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateHandResponse) Reset() {
	*x = EvaluateHandResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateHandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateHandResponse) ProtoMessage() {}

func (x *EvaluateHandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateHandResponse.ProtoReflect.Descriptor instead.
func (*EvaluateHandResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{21}
}

func (x *EvaluateHandResponse) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *EvaluateHandResponse) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *EvaluateHandResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EvaluateHandResponse) GetTiebreakers() []int32 {
	if x != nil {
		return x.Tiebreakers
	}
	return nil
}

func (x *EvaluateHandResponse) GetBest() []*CardInfo {
	if x != nil {
		return x.Best
	}
	return nil
}

type GetNodeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoRequest) Reset() {
	*x = GetNodeInfoRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoRequest) ProtoMessage() {}

func (x *GetNodeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetNodeInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{22}
}

type GetNodeInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ListenAddr    string                 `protobuf:"bytes,2,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Attached      bool                   `protobuf:"varint,4,opt,name=attached,proto3" json:"attached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoResponse) Reset() {
	*x = GetNodeInfoResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoResponse) ProtoMessage() {}

func (x *GetNodeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoResponse.ProtoReflect.Descriptor instead.
func (*GetNodeInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{23}
}

func (x *GetNodeInfoResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetNodeInfoResponse) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *GetNodeInfoResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetNodeInfoResponse) GetAttached() bool {
	if x != nil {
		return x.Attached
	}
	return false
}

type AttachDispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DispatchAddr  string                 `protobuf:"bytes,1,opt,name=dispatch_addr,json=dispatchAddr,proto3" json:"dispatch_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachDispatchRequest) Reset() {
	*x = AttachDispatchRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachDispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachDispatchRequest) ProtoMessage() {}

func (x *AttachDispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachDispatchRequest.ProtoReflect.Descriptor instead.
func (*AttachDispatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{24}
}

func (x *AttachDispatchRequest) GetDispatchAddr() string {
	if x != nil {
		return x.DispatchAddr
	}
	return ""
}

type AttachDispatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachDispatchResponse) Reset() {
	*x = AttachDispatchResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachDispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachDispatchResponse) ProtoMessage() {}

func (x *AttachDispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachDispatchResponse.ProtoReflect.Descriptor instead.
func (*AttachDispatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{25}
}

func (x *AttachDispatchResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type DetachDispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachDispatchRequest) Reset() {
	*x = DetachDispatchRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachDispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachDispatchRequest) ProtoMessage() {}

func (x *DetachDispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachDispatchRequest.ProtoReflect.Descriptor instead.
func (*DetachDispatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{26}
}

type DetachDispatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachDispatchResponse) Reset() {
	*x = DetachDispatchResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachDispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachDispatchResponse) ProtoMessage() {}

func (x *DetachDispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachDispatchResponse.ProtoReflect.Descriptor instead.
func (*DetachDispatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{27}
}

type SubscribeEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{28}
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*Event_PeerMessage
	//	*Event_Log
	//	*Event_GameStart
	//	*Event_HoleCards
	//	*Event_CommunityCards
	//	*Event_RoundStarted
	//	*Event_Action
	//	*Event_AutoFold
	Event         isEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{29}
}

func (x *Event) GetEvent() isEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Event) GetPeerMessage() *PeerMessageEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_PeerMessage); ok {
			return x.PeerMessage
		}
	}
	return nil
}

func (x *Event) GetLog() *LogEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *Event) GetGameStart() *GameStartEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_GameStart); ok {
			return x.GameStart
		}
	}
	return nil
}

func (x *Event) GetHoleCards() *HoleCardsEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_HoleCards); ok {
			return x.HoleCards
		}
	}
	return nil
}

func (x *Event) GetCommunityCards() *CommunityCardsEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_CommunityCards); ok {
			return x.CommunityCards
		}
	}
	return nil
}

func (x *Event) GetRoundStarted() *RoundStartedEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_RoundStarted); ok {
			return x.RoundStarted
		}
	}
	return nil
}

func (x *Event) GetAction() *ActionEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_Action); ok {
			return x.Action
		}
	}
	return nil
}

func (x *Event) GetAutoFold() *AutoFoldEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_AutoFold); ok {
			return x.AutoFold
		}
	}
	return nil
}

type isEvent_Event interface {
	isEvent_Event()
}

type Event_PeerMessage struct {
	PeerMessage *PeerMessageEvent `protobuf:"bytes,1,opt,name=peer_message,json=peerMessage,proto3,oneof"`
}

type Event_Log struct {
	Log *LogEvent `protobuf:"bytes,2,opt,name=log,proto3,oneof"`
}

type Event_GameStart struct {
	GameStart *GameStartEvent `protobuf:"bytes,3,opt,name=game_start,json=gameStart,proto3,oneof"`
}

type Event_HoleCards struct {
	HoleCards *HoleCardsEvent `protobuf:"bytes,4,opt,name=hole_cards,json=holeCards,proto3,oneof"`
}

type Event_CommunityCards struct {
	CommunityCards *CommunityCardsEvent `protobuf:"bytes,5,opt,name=community_cards,json=communityCards,proto3,oneof"`
}

type Event_RoundStarted struct {
	RoundStarted *RoundStartedEvent `protobuf:"bytes,6,opt,name=round_started,json=roundStarted,proto3,oneof"`
}

type Event_Action struct {
	Action *ActionEvent `protobuf:"bytes,7,opt,name=action,proto3,oneof"`
}

type Event_AutoFold struct {
	AutoFold *AutoFoldEvent `protobuf:"bytes,8,opt,name=auto_fold,json=autoFold,proto3,oneof"`
}

func (*Event_PeerMessage) isEvent_Event() {}

func (*Event_Log) isEvent_Event() {}

func (*Event_GameStart) isEvent_Event() {}

func (*Event_HoleCards) isEvent_Event() {}

func (*Event_CommunityCards) isEvent_Event() {}

func (*Event_RoundStarted) isEvent_Event() {}

func (*Event_Action) isEvent_Event() {}

func (*Event_AutoFold) isEvent_Event() {}

// GameStartEvent fires once per game when dispatch has broadcast the seating
// order. A frontend can use order+my_seat to render the table layout.
type GameStartEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Order         []string               `protobuf:"bytes,2,rep,name=order,proto3" json:"order,omitempty"`
	MySeat        int32                  `protobuf:"varint,3,opt,name=my_seat,json=mySeat,proto3" json:"my_seat,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStartEvent) Reset() {
	*x = GameStartEvent{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStartEvent) ProtoMessage() {}

func (x *GameStartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStartEvent.ProtoReflect.Descriptor instead.
func (*GameStartEvent) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{30}
}

func (x *GameStartEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GameStartEvent) GetOrder() []string {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *GameStartEvent) GetMySeat() int32 {
	if x != nil {
		return x.MySeat
	}
	return 0
}

func (x *GameStartEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// HoleCardsEvent carries this node's two hole cards in their full plaintext
// (e.g. "5", "33"). The frontend maps the integer codes to suit+rank.
type HoleCardsEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Card1         string                 `protobuf:"bytes,2,opt,name=card1,proto3" json:"card1,omitempty"`
	Card2         string                 `protobuf:"bytes,3,opt,name=card2,proto3" json:"card2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoleCardsEvent) Reset() {
	*x = HoleCardsEvent{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoleCardsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoleCardsEvent) ProtoMessage() {}

func (x *HoleCardsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoleCardsEvent.ProtoReflect.Descriptor instead.
func (*HoleCardsEvent) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{31}
}

func (x *HoleCardsEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HoleCardsEvent) GetCard1() string {
	if x != nil {
		return x.Card1
	}
	return ""
}

func (x *HoleCardsEvent) GetCard2() string {
	if x != nil {
		return x.Card2
	}
	return ""
}

// CommunityCardsEvent carries the full, cumulative list of revealed
// community cards. Fired once per new card (so the frontend sees flop,
// turn, river in order).
type CommunityCardsEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Cards         []string               `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommunityCardsEvent) Reset() {
	*x = CommunityCardsEvent{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunityCardsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityCardsEvent) ProtoMessage() {}

func (x *CommunityCardsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityCardsEvent.ProtoReflect.Descriptor instead.
func (*CommunityCardsEvent) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{32}
}

func (x *CommunityCardsEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CommunityCardsEvent) GetCards() []string {
	if x != nil {
		return x.Cards
	}
	return nil
}

// RoundStartedEvent marks the start of round_id with proposer at the given
// seat. Frontends drive "whose turn is it" off this event.
type RoundStartedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RoundId       uint64                 `protobuf:"varint,2,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	ProposerSeat  uint32                 `protobuf:"varint,3,opt,name=proposer_seat,json=proposerSeat,proto3" json:"proposer_seat,omitempty"`
	MySeat        int32                  `protobuf:"varint,4,opt,name=my_seat,json=mySeat,proto3" json:"my_seat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundStartedEvent) Reset() {
	*x = RoundStartedEvent{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundStartedEvent) ProtoMessage() {}

func (x *RoundStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundStartedEvent.ProtoReflect.Descriptor instead.
func (*RoundStartedEvent) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{33}
}

func (x *RoundStartedEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RoundStartedEvent) GetRoundId() uint64 {
	if x != nil {
		return x.RoundId
	}
	return 0
}

func (x *RoundStartedEvent) GetProposerSeat() uint32 {
	if x != nil {
		return x.ProposerSeat
	}
	return 0
}

func (x *RoundStartedEvent) GetMySeat() int32 {
	if x != nil {
		return x.MySeat
	}
	return 0
}

// ActionEvent reports the outcome of a single propose/verify attempt:
// the seat that acted, what action they chose, and whether it was
// committed, rejected, or timed out.
type ActionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RoundId       uint64                 `protobuf:"varint,2,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	Attempt       uint32                 `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Seat          int32                  `protobuf:"varint,4,opt,name=seat,proto3" json:"seat,omitempty"`
	Kind          ActionKind             `protobuf:"varint,5,opt,name=kind,proto3,enum=clientrpc.v1.ActionKind" json:"kind,omitempty"`
	Amount        uint64                 `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Outcome       string                 `protobuf:"bytes,7,opt,name=outcome,proto3" json:"outcome,omitempty"` // "committed" | "rejected" | "timeout"
	Reason        string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionEvent) Reset() {
	*x = ActionEvent{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionEvent) ProtoMessage() {}

func (x *ActionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionEvent.ProtoReflect.Descriptor instead.
func (*ActionEvent) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{34}
}

func (x *ActionEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ActionEvent) GetRoundId() uint64 {
	if x != nil {
		return x.RoundId
	}
	return 0
}

func (x *ActionEvent) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ActionEvent) GetSeat() int32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *ActionEvent) GetKind() ActionKind {
	if x != nil {
		return x.Kind
	}
	return ActionKind_ACTION_KIND_FOLD
}

func (x *ActionEvent) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ActionEvent) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *ActionEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// AutoFoldEvent fires when a proposer is auto-folded after exhausting
// their attempt budget.
type AutoFoldEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RoundId       uint64                 `protobuf:"varint,2,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	TargetSeat    uint32                 `protobuf:"varint,3,opt,name=target_seat,json=targetSeat,proto3" json:"target_seat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoFoldEvent) Reset() {
	*x = AutoFoldEvent{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoFoldEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoFoldEvent) ProtoMessage() {}

func (x *AutoFoldEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoFoldEvent.ProtoReflect.Descriptor instead.
func (*AutoFoldEvent) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{35}
}

func (x *AutoFoldEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AutoFoldEvent) GetRoundId() uint64 {
	if x != nil {
		return x.RoundId
	}
	return 0
}

func (x *AutoFoldEvent) GetTargetSeat() uint32 {
	if x != nil {
		return x.TargetSeat
	}
	return 0
}

type PeerMessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	MessageType   string                 `protobuf:"bytes,2,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerMessageEvent) Reset() {
	*x = PeerMessageEvent{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMessageEvent) ProtoMessage() {}

func (x *PeerMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMessageEvent.ProtoReflect.Descriptor instead.
func (*PeerMessageEvent) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{36}
}

func (x *PeerMessageEvent) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *PeerMessageEvent) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *PeerMessageEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// LogEvent mirrors every CLI-visible signal the node emits (shuffle/deal
// progress, round lifecycle, auto-fold, sim harness chatter, etc.) so a
// frontend can observe play without reading stdout.
//
// kind categorizes the event: "log", "game_start", "shuffle", "deal",
// "community", "round", "attempt", "auto_fold", "sim". component is a
// free-form tag (e.g. "runner", "shuffle") to aid filtering. fields carries
// structured extras; cards carries any card values the event wants to
// surface (e.g. {"hole1": "5H", "hole2": "AS"}).
type LogEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs   int64                  `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Component     string                 `protobuf:"bytes,5,opt,name=component,proto3" json:"component,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cards         map[string]string      `protobuf:"bytes,8,rep,name=cards,proto3" json:"cards,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{37}
}

func (x *LogEvent) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *LogEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LogEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LogEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *LogEvent) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *LogEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEvent) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *LogEvent) GetCards() map[string]string {
	if x != nil {
		return x.Cards
	}
	return nil
}

var File_proto_clientrpc_v1_clientrpc_proto protoreflect.FileDescriptor

const file_proto_clientrpc_v1_clientrpc_proto_rawDesc = "" +
	"\n" +
	"\"proto/clientrpc/v1/clientrpc.proto\x12\fclientrpc.v1\"5\n" +
	"\x14CreateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"6\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"3\n" +
	"\x12JoinSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"4\n" +
	"\x13JoinSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x12\n" +
	"\x10ListPeersRequest\"A\n" +
	"\x11ListPeersResponse\x12,\n" +
	"\x05peers\x18\x01 \x03(\v2\x16.clientrpc.v1.PeerInfoR\x05peers\".\n" +
	"\bPeerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\"\x15\n" +
	"\x13ConnectPeersRequest\"?\n" +
	"\x14ConnectPeersResponse\x12'\n" +
	"\x0fconnected_count\x18\x01 \x01(\x05R\x0econnectedCount\"\x15\n" +
	"\x13ListSessionsRequest\"7\n" +
	"\x14ListSessionsResponse\x12\x1f\n" +
	"\vsession_ids\x18\x01 \x03(\tR\n" +
	"sessionIds\"\x12\n" +
	"\x10StartGameRequest\"\x13\n" +
	"\x11StartGameResponse\"[\n" +
	"\x13SubmitActionRequest\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.clientrpc.v1.ActionKindR\x04kind\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\"\x16\n" +
	"\x14SubmitActionResponse\"\x11\n" +
	"\x0fGetCardsRequest\":\n" +
	"\x10GetCardsResponse\x12\x12\n" +
	"\x04hand\x18\x01 \x03(\tR\x04hand\x12\x12\n" +
	"\x04flop\x18\x02 \x03(\tR\x04flop\"\xb0\x01\n" +
	"\bCardInfo\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04suit\x18\x02 \x01(\x05R\x04suit\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank\x12\x14\n" +
	"\x05short\x18\x04 \x01(\tR\x05short\x12\x16\n" +
	"\x06pretty\x18\x05 \x01(\tR\x06pretty\x12\x1b\n" +
	"\tsuit_name\x18\x06 \x01(\tR\bsuitName\x12\x1b\n" +
	"\trank_name\x18\a \x01(\tR\brankName\",\n" +
	"\x14DescribeCardsRequest\x12\x14\n" +
	"\x05cards\x18\x01 \x03(\tR\x05cards\"E\n" +
	"\x15DescribeCardsResponse\x12,\n" +
	"\x05cards\x18\x01 \x03(\v2\x16.clientrpc.v1.CardInfoR\x05cards\"+\n" +
	"\x13EvaluateHandRequest\x12\x14\n" +
	"\x05cards\x18\x01 \x03(\tR\x05cards\"\xc7\x01\n" +
	"\x14EvaluateHandResponse\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\x05R\bcategory\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12 \n" +
	"\vtiebreakers\x18\x04 \x03(\x05R\vtiebreakers\x12*\n" +
	"\x04best\x18\x05 \x03(\v2\x16.clientrpc.v1.CardInfoR\x04best\"\x14\n" +
	"\x12GetNodeInfoRequest\"\x8a\x01\n" +
	"\x13GetNodeInfoResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vlisten_addr\x18\x02 \x01(\tR\n" +
	"listenAddr\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1a\n" +
	"\battached\x18\x04 \x01(\bR\battached\"<\n" +
	"\x15AttachDispatchRequest\x12#\n" +
	"\rdispatch_addr\x18\x01 \x01(\tR\fdispatchAddr\"1\n" +
	"\x16AttachDispatchResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\x17\n" +
	"\x15DetachDispatchRequest\"\x18\n" +
	"\x16DetachDispatchResponse\"\x18\n" +
	"\x16SubscribeEventsRequest\"\x86\x04\n" +
	"\x05Event\x12C\n" +
	"\fpeer_message\x18\x01 \x01(\v2\x1e.clientrpc.v1.PeerMessageEventH\x00R\vpeerMessage\x12*\n" +
	"\x03log\x18\x02 \x01(\v2\x16.clientrpc.v1.LogEventH\x00R\x03log\x12=\n" +
	"\n" +
	"game_start\x18\x03 \x01(\v2\x1c.clientrpc.v1.GameStartEventH\x00R\tgameStart\x12=\n" +
	"\n" +
	"hole_cards\x18\x04 \x01(\v2\x1c.clientrpc.v1.HoleCardsEventH\x00R\tholeCards\x12L\n" +
	"\x0fcommunity_cards\x18\x05 \x01(\v2!.clientrpc.v1.CommunityCardsEventH\x00R\x0ecommunityCards\x12F\n" +
	"\rround_started\x18\x06 \x01(\v2\x1f.clientrpc.v1.RoundStartedEventH\x00R\froundStarted\x123\n" +
	"\x06action\x18\a \x01(\v2\x19.clientrpc.v1.ActionEventH\x00R\x06action\x12:\n" +
	"\tauto_fold\x18\b \x01(\v2\x1b.clientrpc.v1.AutoFoldEventH\x00R\bautoFoldB\a\n" +
	"\x05event\"w\n" +
	"\x0eGameStartEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05order\x18\x02 \x03(\tR\x05order\x12\x17\n" +
	"\amy_seat\x18\x03 \x01(\x05R\x06mySeat\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\"U\n" +
	"\x0eHoleCardsEvent\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05card1\x18\x02 \x01(\tR\x05card1\x12\x14\n" +
	"\x05card2\x18\x03 \x01(\tR\x05card2\"D\n" +
	"\x13CommunityCardsEvent\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05cards\x18\x02 \x03(\tR\x05cards\"\x85\x01\n" +
	"\x11RoundStartedEvent\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bround_id\x18\x02 \x01(\x04R\aroundId\x12#\n" +
	"\rproposer_seat\x18\x03 \x01(\rR\fproposerSeat\x12\x17\n" +
	"\amy_seat\x18\x04 \x01(\x05R\x06mySeat\"\xe7\x01\n" +
	"\vActionEvent\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bround_id\x18\x02 \x01(\x04R\aroundId\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\rR\aattempt\x12\x12\n" +
	"\x04seat\x18\x04 \x01(\x05R\x04seat\x12,\n" +
	"\x04kind\x18\x05 \x01(\x0e2\x18.clientrpc.v1.ActionKindR\x04kind\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x04R\x06amount\x12\x18\n" +
	"\aoutcome\x18\a \x01(\tR\aoutcome\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\"d\n" +
	"\rAutoFoldEvent\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bround_id\x18\x02 \x01(\x04R\aroundId\x12\x1f\n" +
	"\vtarget_seat\x18\x03 \x01(\rR\n" +
	"targetSeat\"c\n" +
	"\x10PeerMessageEvent\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12!\n" +
	"\fmessage_type\x18\x02 \x01(\tR\vmessageType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\x9b\x03\n" +
	"\bLogEvent\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x03R\vtimestampNs\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x1c\n" +
	"\tcomponent\x18\x05 \x01(\tR\tcomponent\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12:\n" +
	"\x06fields\x18\a \x03(\v2\".clientrpc.v1.LogEvent.FieldsEntryR\x06fields\x127\n" +
	"\x05cards\x18\b \x03(\v2!.clientrpc.v1.LogEvent.CardsEntryR\x05cards\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"CardsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*f\n" +
	"\n" +
	"ActionKind\x12\x14\n" +
	"\x10ACTION_KIND_FOLD\x10\x00\x12\x15\n" +
	"\x11ACTION_KIND_CHECK\x10\x01\x12\x14\n" +
	"\x10ACTION_KIND_CALL\x10\x02\x12\x15\n" +
	"\x11ACTION_KIND_RAISE\x10\x032\xb4\t\n" +
	"\tPokerNode\x12X\n" +
	"\rCreateSession\x12\".clientrpc.v1.CreateSessionRequest\x1a#.clientrpc.v1.CreateSessionResponse\x12R\n" +
	"\vJoinSession\x12 .clientrpc.v1.JoinSessionRequest\x1a!.clientrpc.v1.JoinSessionResponse\x12L\n" +
	"\tListPeers\x12\x1e.clientrpc.v1.ListPeersRequest\x1a\x1f.clientrpc.v1.ListPeersResponse\x12U\n" +
	"\fConnectPeers\x12!.clientrpc.v1.ConnectPeersRequest\x1a\".clientrpc.v1.ConnectPeersResponse\x12U\n" +
	"\fListSessions\x12!.clientrpc.v1.ListSessionsRequest\x1a\".clientrpc.v1.ListSessionsResponse\x12L\n" +
	"\tStartGame\x12\x1e.clientrpc.v1.StartGameRequest\x1a\x1f.clientrpc.v1.StartGameResponse\x12U\n" +
	"\fSubmitAction\x12!.clientrpc.v1.SubmitActionRequest\x1a\".clientrpc.v1.SubmitActionResponse\x12I\n" +
	"\bGetCards\x12\x1d.clientrpc.v1.GetCardsRequest\x1a\x1e.clientrpc.v1.GetCardsResponse\x12X\n" +
	"\rDescribeCards\x12\".clientrpc.v1.DescribeCardsRequest\x1a#.clientrpc.v1.DescribeCardsResponse\x12U\n" +
	"\fEvaluateHand\x12!.clientrpc.v1.EvaluateHandRequest\x1a\".clientrpc.v1.EvaluateHandResponse\x12R\n" +
	"\vGetNodeInfo\x12 .clientrpc.v1.GetNodeInfoRequest\x1a!.clientrpc.v1.GetNodeInfoResponse\x12[\n" +
	"\x0eAttachDispatch\x12#.clientrpc.v1.AttachDispatchRequest\x1a$.clientrpc.v1.AttachDispatchResponse\x12[\n" +
	"\x0eDetachDispatch\x12#.clientrpc.v1.DetachDispatchRequest\x1a$.clientrpc.v1.DetachDispatchResponse\x12N\n" +
	"\x0fSubscribeEvents\x12$.clientrpc.v1.SubscribeEventsRequest\x1a\x13.clientrpc.v1.Event0\x01B=Z;github.com/sivepanda/p2poker/internal/clientrpc/clientrpcpbb\x06proto3"

var (
	file_proto_clientrpc_v1_clientrpc_proto_rawDescOnce sync.Once
	file_proto_clientrpc_v1_clientrpc_proto_rawDescData []byte
)

func file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP() []byte {
	file_proto_clientrpc_v1_clientrpc_proto_rawDescOnce.Do(func() {
		file_proto_clientrpc_v1_clientrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_clientrpc_v1_clientrpc_proto_rawDesc), len(file_proto_clientrpc_v1_clientrpc_proto_rawDesc)))
	})
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescData
}

var file_proto_clientrpc_v1_clientrpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_clientrpc_v1_clientrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_proto_clientrpc_v1_clientrpc_proto_goTypes = []any{
	(ActionKind)(0),                // 0: clientrpc.v1.ActionKind
	(*CreateSessionRequest)(nil),   // 1: clientrpc.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),  // 2: clientrpc.v1.CreateSessionResponse
	(*JoinSessionRequest)(nil),     // 3: clientrpc.v1.JoinSessionRequest
	(*JoinSessionResponse)(nil),    // 4: clientrpc.v1.JoinSessionResponse
	(*ListPeersRequest)(nil),       // 5: clientrpc.v1.ListPeersRequest
	(*ListPeersResponse)(nil),      // 6: clientrpc.v1.ListPeersResponse
	(*PeerInfo)(nil),               // 7: clientrpc.v1.PeerInfo
	(*ConnectPeersRequest)(nil),    // 8: clientrpc.v1.ConnectPeersRequest
	(*ConnectPeersResponse)(nil),   // 9: clientrpc.v1.ConnectPeersResponse
	(*ListSessionsRequest)(nil),    // 10: clientrpc.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),   // 11: clientrpc.v1.ListSessionsResponse
	(*StartGameRequest)(nil),       // 12: clientrpc.v1.StartGameRequest
	(*StartGameResponse)(nil),      // 13: clientrpc.v1.StartGameResponse
	(*SubmitActionRequest)(nil),    // 14: clientrpc.v1.SubmitActionRequest
	(*SubmitActionResponse)(nil),   // 15: clientrpc.v1.SubmitActionResponse
	(*GetCardsRequest)(nil),        // 16: clientrpc.v1.GetCardsRequest
	(*GetCardsResponse)(nil),       // 17: clientrpc.v1.GetCardsResponse
	(*CardInfo)(nil),               // 18: clientrpc.v1.CardInfo
	(*DescribeCardsRequest)(nil),   // 19: clientrpc.v1.DescribeCardsRequest
	(*DescribeCardsResponse)(nil),  // 20: clientrpc.v1.DescribeCardsResponse
	(*EvaluateHandRequest)(nil),    // 21: clientrpc.v1.EvaluateHandRequest
	(*EvaluateHandResponse)(nil),   // 22: clientrpc.v1.EvaluateHandResponse
	(*GetNodeInfoRequest)(nil),     // 23: clientrpc.v1.GetNodeInfoRequest
	(*GetNodeInfoResponse)(nil),    // 24: clientrpc.v1.GetNodeInfoResponse
	(*AttachDispatchRequest)(nil),  // 25: clientrpc.v1.AttachDispatchRequest
	(*AttachDispatchResponse)(nil), // 26: clientrpc.v1.AttachDispatchResponse
	(*DetachDispatchRequest)(nil),  // 27: clientrpc.v1.DetachDispatchRequest
	(*DetachDispatchResponse)(nil), // 28: clientrpc.v1.DetachDispatchResponse
	(*SubscribeEventsRequest)(nil), // 29: clientrpc.v1.SubscribeEventsRequest
	(*Event)(nil),                  // 30: clientrpc.v1.Event
	(*GameStartEvent)(nil),         // 31: clientrpc.v1.GameStartEvent
	(*HoleCardsEvent)(nil),         // 32: clientrpc.v1.HoleCardsEvent
	(*CommunityCardsEvent)(nil),    // 33: clientrpc.v1.CommunityCardsEvent
	(*RoundStartedEvent)(nil),      // 34: clientrpc.v1.RoundStartedEvent
	(*ActionEvent)(nil),            // 35: clientrpc.v1.ActionEvent
	(*AutoFoldEvent)(nil),          // 36: clientrpc.v1.AutoFoldEvent
	(*PeerMessageEvent)(nil),       // 37: clientrpc.v1.PeerMessageEvent
	(*LogEvent)(nil),               // 38: clientrpc.v1.LogEvent
	nil,                            // 39: clientrpc.v1.LogEvent.FieldsEntry
	nil,                            // 40: clientrpc.v1.LogEvent.CardsEntry
}
var file_proto_clientrpc_v1_clientrpc_proto_depIdxs = []int32{
	7,  // 0: clientrpc.v1.ListPeersResponse.peers:type_name -> clientrpc.v1.PeerInfo
	0,  // 1: clientrpc.v1.SubmitActionRequest.kind:type_name -> clientrpc.v1.ActionKind
	18, // 2: clientrpc.v1.DescribeCardsResponse.cards:type_name -> clientrpc.v1.CardInfo
	18, // 3: clientrpc.v1.EvaluateHandResponse.best:type_name -> clientrpc.v1.CardInfo
	37, // 4: clientrpc.v1.Event.peer_message:type_name -> clientrpc.v1.PeerMessageEvent
	38, // 5: clientrpc.v1.Event.log:type_name -> clientrpc.v1.LogEvent
	31, // 6: clientrpc.v1.Event.game_start:type_name -> clientrpc.v1.GameStartEvent
	32, // 7: clientrpc.v1.Event.hole_cards:type_name -> clientrpc.v1.HoleCardsEvent
	33, // 8: clientrpc.v1.Event.community_cards:type_name -> clientrpc.v1.CommunityCardsEvent
	34, // 9: clientrpc.v1.Event.round_started:type_name -> clientrpc.v1.RoundStartedEvent
	35, // 10: clientrpc.v1.Event.action:type_name -> clientrpc.v1.ActionEvent
	36, // 11: clientrpc.v1.Event.auto_fold:type_name -> clientrpc.v1.AutoFoldEvent
	0,  // 12: clientrpc.v1.ActionEvent.kind:type_name -> clientrpc.v1.ActionKind
	39, // 13: clientrpc.v1.LogEvent.fields:type_name -> clientrpc.v1.LogEvent.FieldsEntry
	40, // 14: clientrpc.v1.LogEvent.cards:type_name -> clientrpc.v1.LogEvent.CardsEntry
	1,  // 15: clientrpc.v1.PokerNode.CreateSession:input_type -> clientrpc.v1.CreateSessionRequest
	3,  // 16: clientrpc.v1.PokerNode.JoinSession:input_type -> clientrpc.v1.JoinSessionRequest
	5,  // 17: clientrpc.v1.PokerNode.ListPeers:input_type -> clientrpc.v1.ListPeersRequest
	8,  // 18: clientrpc.v1.PokerNode.ConnectPeers:input_type -> clientrpc.v1.ConnectPeersRequest
	10, // 19: clientrpc.v1.PokerNode.ListSessions:input_type -> clientrpc.v1.ListSessionsRequest
	12, // 20: clientrpc.v1.PokerNode.StartGame:input_type -> clientrpc.v1.StartGameRequest
	14, // 21: clientrpc.v1.PokerNode.SubmitAction:input_type -> clientrpc.v1.SubmitActionRequest
	16, // 22: clientrpc.v1.PokerNode.GetCards:input_type -> clientrpc.v1.GetCardsRequest
	19, // 23: clientrpc.v1.PokerNode.DescribeCards:input_type -> clientrpc.v1.DescribeCardsRequest
	21, // 24: clientrpc.v1.PokerNode.EvaluateHand:input_type -> clientrpc.v1.EvaluateHandRequest
	23, // 25: clientrpc.v1.PokerNode.GetNodeInfo:input_type -> clientrpc.v1.GetNodeInfoRequest
	25, // 26: clientrpc.v1.PokerNode.AttachDispatch:input_type -> clientrpc.v1.AttachDispatchRequest
	27, // 27: clientrpc.v1.PokerNode.DetachDispatch:input_type -> clientrpc.v1.DetachDispatchRequest
	29, // 28: clientrpc.v1.PokerNode.SubscribeEvents:input_type -> clientrpc.v1.SubscribeEventsRequest
	2,  // 29: clientrpc.v1.PokerNode.CreateSession:output_type -> clientrpc.v1.CreateSessionResponse
	4,  // 30: clientrpc.v1.PokerNode.JoinSession:output_type -> clientrpc.v1.JoinSessionResponse
	6,  // 31: clientrpc.v1.PokerNode.ListPeers:output_type -> clientrpc.v1.ListPeersResponse
	9,  // 32: clientrpc.v1.PokerNode.ConnectPeers:output_type -> clientrpc.v1.ConnectPeersResponse
	11, // 33: clientrpc.v1.PokerNode.ListSessions:output_type -> clientrpc.v1.ListSessionsResponse
	13, // 34: clientrpc.v1.PokerNode.StartGame:output_type -> clientrpc.v1.StartGameResponse
	15, // 35: clientrpc.v1.PokerNode.SubmitAction:output_type -> clientrpc.v1.SubmitActionResponse
	17, // 36: clientrpc.v1.PokerNode.GetCards:output_type -> clientrpc.v1.GetCardsResponse
	20, // 37: clientrpc.v1.PokerNode.DescribeCards:output_type -> clientrpc.v1.DescribeCardsResponse
	22, // 38: clientrpc.v1.PokerNode.EvaluateHand:output_type -> clientrpc.v1.EvaluateHandResponse
	24, // 39: clientrpc.v1.PokerNode.GetNodeInfo:output_type -> clientrpc.v1.GetNodeInfoResponse
	26, // 40: clientrpc.v1.PokerNode.AttachDispatch:output_type -> clientrpc.v1.AttachDispatchResponse
	28, // 41: clientrpc.v1.PokerNode.DetachDispatch:output_type -> clientrpc.v1.DetachDispatchResponse
	30, // 42: clientrpc.v1.PokerNode.SubscribeEvents:output_type -> clientrpc.v1.Event
	29, // [29:43] is the sub-list for method output_type
	15, // [15:29] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_clientrpc_v1_clientrpc_proto_init() }
func file_proto_clientrpc_v1_clientrpc_proto_init() {
	if File_proto_clientrpc_v1_clientrpc_proto != nil {
		return
	}
	file_proto_clientrpc_v1_clientrpc_proto_msgTypes[29].OneofWrappers = []any{
		(*Event_PeerMessage)(nil),
		(*Event_Log)(nil),
		(*Event_GameStart)(nil),
		(*Event_HoleCards)(nil),
		(*Event_CommunityCards)(nil),
		(*Event_RoundStarted)(nil),
		(*Event_Action)(nil),
		(*Event_AutoFold)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_clientrpc_v1_clientrpc_proto_rawDesc), len(file_proto_clientrpc_v1_clientrpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_clientrpc_v1_clientrpc_proto_goTypes,
		DependencyIndexes: file_proto_clientrpc_v1_clientrpc_proto_depIdxs,
		EnumInfos:         file_proto_clientrpc_v1_clientrpc_proto_enumTypes,
		MessageInfos:      file_proto_clientrpc_v1_clientrpc_proto_msgTypes,
	}.Build()
	File_proto_clientrpc_v1_clientrpc_proto = out.File
	file_proto_clientrpc_v1_clientrpc_proto_goTypes = nil
	file_proto_clientrpc_v1_clientrpc_proto_depIdxs = nil
}
