// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/clientrpc/v1/clientrpc.proto

package clientrpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PokerNode_CreateSession_FullMethodName   = "/clientrpc.v1.PokerNode/CreateSession"
	PokerNode_JoinSession_FullMethodName     = "/clientrpc.v1.PokerNode/JoinSession"
	PokerNode_ListPeers_FullMethodName       = "/clientrpc.v1.PokerNode/ListPeers"
	PokerNode_ConnectPeers_FullMethodName    = "/clientrpc.v1.PokerNode/ConnectPeers"
	PokerNode_ListSessions_FullMethodName    = "/clientrpc.v1.PokerNode/ListSessions"
	PokerNode_StartGame_FullMethodName       = "/clientrpc.v1.PokerNode/StartGame"
	PokerNode_SubmitAction_FullMethodName    = "/clientrpc.v1.PokerNode/SubmitAction"
	PokerNode_GetCards_FullMethodName        = "/clientrpc.v1.PokerNode/GetCards"
	PokerNode_DescribeCards_FullMethodName   = "/clientrpc.v1.PokerNode/DescribeCards"
	PokerNode_EvaluateHand_FullMethodName    = "/clientrpc.v1.PokerNode/EvaluateHand"
	PokerNode_GetNodeInfo_FullMethodName     = "/clientrpc.v1.PokerNode/GetNodeInfo"
	PokerNode_AttachDispatch_FullMethodName  = "/clientrpc.v1.PokerNode/AttachDispatch"
	PokerNode_DetachDispatch_FullMethodName  = "/clientrpc.v1.PokerNode/DetachDispatch"
	PokerNode_SubscribeEvents_FullMethodName = "/clientrpc.v1.PokerNode/SubscribeEvents"
)

// PokerNodeClient is the client API for PokerNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PokerNodeClient interface {
	// Lobby
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	JoinSession(ctx context.Context, in *JoinSessionRequest, opts ...grpc.CallOption) (*JoinSessionResponse, error)
	ListPeers(ctx context.Context, in *ListPeersRequest, opts ...grpc.CallOption) (*ListPeersResponse, error)
	ConnectPeers(ctx context.Context, in *ConnectPeersRequest, opts ...grpc.CallOption) (*ConnectPeersResponse, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*StartGameResponse, error)
	// Gameplay
	SubmitAction(ctx context.Context, in *SubmitActionRequest, opts ...grpc.CallOption) (*SubmitActionResponse, error)
	GetCards(ctx context.Context, in *GetCardsRequest, opts ...grpc.CallOption) (*GetCardsResponse, error)
	// Card decode + hand evaluation. Pure functions over the deck-int wire
	// format; safe to call any time. Frontends use these instead of
	// re-implementing suit/rank mapping or hand ranking.
	DescribeCards(ctx context.Context, in *DescribeCardsRequest, opts ...grpc.CallOption) (*DescribeCardsResponse, error)
	EvaluateHand(ctx context.Context, in *EvaluateHandRequest, opts ...grpc.CallOption) (*EvaluateHandResponse, error)
	// Node
	GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error)
	AttachDispatch(ctx context.Context, in *AttachDispatchRequest, opts ...grpc.CallOption) (*AttachDispatchResponse, error)
	DetachDispatch(ctx context.Context, in *DetachDispatchRequest, opts ...grpc.CallOption) (*DetachDispatchResponse, error)
	// Events: server-side stream, frontend subscribes once
	SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
}

type pokerNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewPokerNodeClient(cc grpc.ClientConnInterface) PokerNodeClient {
	return &pokerNodeClient{cc}
}

func (c *pokerNodeClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, PokerNode_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerNodeClient) JoinSession(ctx context.Context, in *JoinSessionRequest, opts ...grpc.CallOption) (*JoinSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinSessionResponse)
	err := c.cc.Invoke(ctx, PokerNode_JoinSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerNodeClient) ListPeers(ctx context.Context, in *ListPeersRequest, opts ...grpc.CallOption) (*ListPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPeersResponse)
	err := c.cc.Invoke(ctx, PokerNode_ListPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerNodeClient) ConnectPeers(ctx context.Context, in *ConnectPeersRequest, opts ...grpc.CallOption) (*ConnectPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectPeersResponse)
	err := c.cc.Invoke(ctx, PokerNode_ConnectPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerNodeClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, PokerNode_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerNodeClient) StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*StartGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartGameResponse)
	err := c.cc.Invoke(ctx, PokerNode_StartGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerNodeClient) SubmitAction(ctx context.Context, in *SubmitActionRequest, opts ...grpc.CallOption) (*SubmitActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitActionResponse)
	err := c.cc.Invoke(ctx, PokerNode_SubmitAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerNodeClient) GetCards(ctx context.Context, in *GetCardsRequest, opts ...grpc.CallOption) (*GetCardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCardsResponse)
	err := c.cc.Invoke(ctx, PokerNode_GetCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerNodeClient) DescribeCards(ctx context.Context, in *DescribeCardsRequest, opts ...grpc.CallOption) (*DescribeCardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeCardsResponse)
	err := c.cc.Invoke(ctx, PokerNode_DescribeCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerNodeClient) EvaluateHand(ctx context.Context, in *EvaluateHandRequest, opts ...grpc.CallOption) (*EvaluateHandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateHandResponse)
	err := c.cc.Invoke(ctx, PokerNode_EvaluateHand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerNodeClient) GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeInfoResponse)
	err := c.cc.Invoke(ctx, PokerNode_GetNodeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerNodeClient) AttachDispatch(ctx context.Context, in *AttachDispatchRequest, opts ...grpc.CallOption) (*AttachDispatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachDispatchResponse)
	err := c.cc.Invoke(ctx, PokerNode_AttachDispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerNodeClient) DetachDispatch(ctx context.Context, in *DetachDispatchRequest, opts ...grpc.CallOption) (*DetachDispatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetachDispatchResponse)
	err := c.cc.Invoke(ctx, PokerNode_DetachDispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerNodeClient) SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PokerNode_ServiceDesc.Streams[0], PokerNode_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeEventsRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PokerNode_SubscribeEventsClient = grpc.ServerStreamingClient[Event]

// PokerNodeServer is the server API for PokerNode service.
// All implementations must embed UnimplementedPokerNodeServer
// for forward compatibility.
type PokerNodeServer interface {
	// Lobby
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	JoinSession(context.Context, *JoinSessionRequest) (*JoinSessionResponse, error)
	ListPeers(context.Context, *ListPeersRequest) (*ListPeersResponse, error)
	ConnectPeers(context.Context, *ConnectPeersRequest) (*ConnectPeersResponse, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	StartGame(context.Context, *StartGameRequest) (*StartGameResponse, error)
	// Gameplay
	SubmitAction(context.Context, *SubmitActionRequest) (*SubmitActionResponse, error)
	GetCards(context.Context, *GetCardsRequest) (*GetCardsResponse, error)
	// Card decode + hand evaluation. Pure functions over the deck-int wire
	// format; safe to call any time. Frontends use these instead of
	// re-implementing suit/rank mapping or hand ranking.
	DescribeCards(context.Context, *DescribeCardsRequest) (*DescribeCardsResponse, error)
	EvaluateHand(context.Context, *EvaluateHandRequest) (*EvaluateHandResponse, error)
	// Node
	GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error)
	AttachDispatch(context.Context, *AttachDispatchRequest) (*AttachDispatchResponse, error)
	DetachDispatch(context.Context, *DetachDispatchRequest) (*DetachDispatchResponse, error)
	// Events: server-side stream, frontend subscribes once
	SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[Event]) error
	mustEmbedUnimplementedPokerNodeServer()
}

// UnimplementedPokerNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPokerNodeServer struct{}

func (UnimplementedPokerNodeServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedPokerNodeServer) JoinSession(context.Context, *JoinSessionRequest) (*JoinSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinSession not implemented")
}
func (UnimplementedPokerNodeServer) ListPeers(context.Context, *ListPeersRequest) (*ListPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPeers not implemented")
}
func (UnimplementedPokerNodeServer) ConnectPeers(context.Context, *ConnectPeersRequest) (*ConnectPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectPeers not implemented")
}
func (UnimplementedPokerNodeServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedPokerNodeServer) StartGame(context.Context, *StartGameRequest) (*StartGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartGame not implemented")
}
func (UnimplementedPokerNodeServer) SubmitAction(context.Context, *SubmitActionRequest) (*SubmitActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitAction not implemented")
}
func (UnimplementedPokerNodeServer) GetCards(context.Context, *GetCardsRequest) (*GetCardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCards not implemented")
}
func (UnimplementedPokerNodeServer) DescribeCards(context.Context, *DescribeCardsRequest) (*DescribeCardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeCards not implemented")
}
func (UnimplementedPokerNodeServer) EvaluateHand(context.Context, *EvaluateHandRequest) (*EvaluateHandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateHand not implemented")
}
func (UnimplementedPokerNodeServer) GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeInfo not implemented")
}
func (UnimplementedPokerNodeServer) AttachDispatch(context.Context, *AttachDispatchRequest) (*AttachDispatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachDispatch not implemented")
}
func (UnimplementedPokerNodeServer) DetachDispatch(context.Context, *DetachDispatchRequest) (*DetachDispatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetachDispatch not implemented")
}
func (UnimplementedPokerNodeServer) SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedPokerNodeServer) mustEmbedUnimplementedPokerNodeServer() {}
func (UnimplementedPokerNodeServer) testEmbeddedByValue()                   {}

// UnsafePokerNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PokerNodeServer will
// result in compilation errors.
type UnsafePokerNodeServer interface {
	mustEmbedUnimplementedPokerNodeServer()
}

func RegisterPokerNodeServer(s grpc.ServiceRegistrar, srv PokerNodeServer) {
	// If the following call panics, it indicates UnimplementedPokerNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PokerNode_ServiceDesc, srv)
}

func _PokerNode_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerNodeServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerNode_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerNodeServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerNode_JoinSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerNodeServer).JoinSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerNode_JoinSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerNodeServer).JoinSession(ctx, req.(*JoinSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerNode_ListPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerNodeServer).ListPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerNode_ListPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerNodeServer).ListPeers(ctx, req.(*ListPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerNode_ConnectPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerNodeServer).ConnectPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerNode_ConnectPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerNodeServer).ConnectPeers(ctx, req.(*ConnectPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerNode_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerNodeServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerNode_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerNodeServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerNode_StartGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerNodeServer).StartGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerNode_StartGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerNodeServer).StartGame(ctx, req.(*StartGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerNode_SubmitAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerNodeServer).SubmitAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerNode_SubmitAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerNodeServer).SubmitAction(ctx, req.(*SubmitActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerNode_GetCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerNodeServer).GetCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerNode_GetCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerNodeServer).GetCards(ctx, req.(*GetCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerNode_DescribeCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerNodeServer).DescribeCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerNode_DescribeCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerNodeServer).DescribeCards(ctx, req.(*DescribeCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerNode_EvaluateHand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateHandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerNodeServer).EvaluateHand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerNode_EvaluateHand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerNodeServer).EvaluateHand(ctx, req.(*EvaluateHandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerNode_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerNodeServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerNode_GetNodeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerNodeServer).GetNodeInfo(ctx, req.(*GetNodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerNode_AttachDispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachDispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerNodeServer).AttachDispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerNode_AttachDispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerNodeServer).AttachDispatch(ctx, req.(*AttachDispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerNode_DetachDispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachDispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerNodeServer).DetachDispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerNode_DetachDispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerNodeServer).DetachDispatch(ctx, req.(*DetachDispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerNode_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PokerNodeServer).SubscribeEvents(m, &grpc.GenericServerStream[SubscribeEventsRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PokerNode_SubscribeEventsServer = grpc.ServerStreamingServer[Event]

// PokerNode_ServiceDesc is the grpc.ServiceDesc for PokerNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PokerNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clientrpc.v1.PokerNode",
	HandlerType: (*PokerNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _PokerNode_CreateSession_Handler,
		},
		{
			MethodName: "JoinSession",
			Handler:    _PokerNode_JoinSession_Handler,
		},
		{
			MethodName: "ListPeers",
			Handler:    _PokerNode_ListPeers_Handler,
		},
		{
			MethodName: "ConnectPeers",
			Handler:    _PokerNode_ConnectPeers_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _PokerNode_ListSessions_Handler,
		},
		{
			MethodName: "StartGame",
			Handler:    _PokerNode_StartGame_Handler,
		},
		{
			MethodName: "SubmitAction",
			Handler:    _PokerNode_SubmitAction_Handler,
		},
		{
			MethodName: "GetCards",
			Handler:    _PokerNode_GetCards_Handler,
		},
		{
			MethodName: "DescribeCards",
			Handler:    _PokerNode_DescribeCards_Handler,
		},
		{
			MethodName: "EvaluateHand",
			Handler:    _PokerNode_EvaluateHand_Handler,
		},
		{
			MethodName: "GetNodeInfo",
			Handler:    _PokerNode_GetNodeInfo_Handler,
		},
		{
			MethodName: "AttachDispatch",
			Handler:    _PokerNode_AttachDispatch_Handler,
		},
		{
			MethodName: "DetachDispatch",
			Handler:    _PokerNode_DetachDispatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvents",
			Handler:       _PokerNode_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/clientrpc/v1/clientrpc.proto",
}
