// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/clientrpc/v1/clientrpc.proto

package clientrpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type JoinSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinSessionRequest) Reset() {
	*x = JoinSessionRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSessionRequest) ProtoMessage() {}

func (x *JoinSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSessionRequest.ProtoReflect.Descriptor instead.
func (*JoinSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{2}
}

func (x *JoinSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type JoinSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinSessionResponse) Reset() {
	*x = JoinSessionResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSessionResponse) ProtoMessage() {}

func (x *JoinSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSessionResponse.ProtoReflect.Descriptor instead.
func (*JoinSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{3}
}

func (x *JoinSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersRequest) Reset() {
	*x = ListPeersRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersRequest) ProtoMessage() {}

func (x *ListPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersRequest.ProtoReflect.Descriptor instead.
func (*ListPeersRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{4}
}

type ListPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersResponse) Reset() {
	*x = ListPeersResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersResponse) ProtoMessage() {}

func (x *ListPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersResponse.ProtoReflect.Descriptor instead.
func (*ListPeersResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{5}
}

func (x *ListPeersResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{6}
}

func (x *PeerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PeerInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type ConnectPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectPeersRequest) Reset() {
	*x = ConnectPeersRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectPeersRequest) ProtoMessage() {}

func (x *ConnectPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectPeersRequest.ProtoReflect.Descriptor instead.
func (*ConnectPeersRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{7}
}

type ConnectPeersResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConnectedCount int32                  `protobuf:"varint,1,opt,name=connected_count,json=connectedCount,proto3" json:"connected_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectPeersResponse) Reset() {
	*x = ConnectPeersResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectPeersResponse) ProtoMessage() {}

func (x *ConnectPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectPeersResponse.ProtoReflect.Descriptor instead.
func (*ConnectPeersResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{8}
}

func (x *ConnectPeersResponse) GetConnectedCount() int32 {
	if x != nil {
		return x.ConnectedCount
	}
	return 0
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{9}
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionIds    []string               `protobuf:"bytes,1,rep,name=session_ids,json=sessionIds,proto3" json:"session_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{10}
}

func (x *ListSessionsResponse) GetSessionIds() []string {
	if x != nil {
		return x.SessionIds
	}
	return nil
}

type GetNodeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoRequest) Reset() {
	*x = GetNodeInfoRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoRequest) ProtoMessage() {}

func (x *GetNodeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetNodeInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{11}
}

type GetNodeInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ListenAddr    string                 `protobuf:"bytes,2,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoResponse) Reset() {
	*x = GetNodeInfoResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoResponse) ProtoMessage() {}

func (x *GetNodeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoResponse.ProtoReflect.Descriptor instead.
func (*GetNodeInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{12}
}

func (x *GetNodeInfoResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetNodeInfoResponse) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *GetNodeInfoResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SubscribeEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{13}
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*Event_PeerMessage
	Event         isEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{14}
}

func (x *Event) GetEvent() isEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Event) GetPeerMessage() *PeerMessageEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_PeerMessage); ok {
			return x.PeerMessage
		}
	}
	return nil
}

type isEvent_Event interface {
	isEvent_Event()
}

type Event_PeerMessage struct {
	PeerMessage *PeerMessageEvent `protobuf:"bytes,1,opt,name=peer_message,json=peerMessage,proto3,oneof"`
}

func (*Event_PeerMessage) isEvent_Event() {}

type PeerMessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	MessageType   string                 `protobuf:"bytes,2,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerMessageEvent) Reset() {
	*x = PeerMessageEvent{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMessageEvent) ProtoMessage() {}

func (x *PeerMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMessageEvent.ProtoReflect.Descriptor instead.
func (*PeerMessageEvent) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{15}
}

func (x *PeerMessageEvent) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *PeerMessageEvent) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *PeerMessageEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_proto_clientrpc_v1_clientrpc_proto protoreflect.FileDescriptor

const file_proto_clientrpc_v1_clientrpc_proto_rawDesc = "" +
	"\n" +
	"\"proto/clientrpc/v1/clientrpc.proto\x12\fclientrpc.v1\"5\n" +
	"\x14CreateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"6\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"3\n" +
	"\x12JoinSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"4\n" +
	"\x13JoinSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x12\n" +
	"\x10ListPeersRequest\"A\n" +
	"\x11ListPeersResponse\x12,\n" +
	"\x05peers\x18\x01 \x03(\v2\x16.clientrpc.v1.PeerInfoR\x05peers\".\n" +
	"\bPeerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\"\x15\n" +
	"\x13ConnectPeersRequest\"?\n" +
	"\x14ConnectPeersResponse\x12'\n" +
	"\x0fconnected_count\x18\x01 \x01(\x05R\x0econnectedCount\"\x15\n" +
	"\x13ListSessionsRequest\"7\n" +
	"\x14ListSessionsResponse\x12\x1f\n" +
	"\vsession_ids\x18\x01 \x03(\tR\n" +
	"sessionIds\"\x14\n" +
	"\x12GetNodeInfoRequest\"n\n" +
	"\x13GetNodeInfoResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vlisten_addr\x18\x02 \x01(\tR\n" +
	"listenAddr\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\x18\n" +
	"\x16SubscribeEventsRequest\"U\n" +
	"\x05Event\x12C\n" +
	"\fpeer_message\x18\x01 \x01(\v2\x1e.clientrpc.v1.PeerMessageEventH\x00R\vpeerMessageB\a\n" +
	"\x05event\"c\n" +
	"\x10PeerMessageEvent\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12!\n" +
	"\fmessage_type\x18\x02 \x01(\tR\vmessageType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload2\xd9\x04\n" +
	"\tPokerNode\x12X\n" +
	"\rCreateSession\x12\".clientrpc.v1.CreateSessionRequest\x1a#.clientrpc.v1.CreateSessionResponse\x12R\n" +
	"\vJoinSession\x12 .clientrpc.v1.JoinSessionRequest\x1a!.clientrpc.v1.JoinSessionResponse\x12L\n" +
	"\tListPeers\x12\x1e.clientrpc.v1.ListPeersRequest\x1a\x1f.clientrpc.v1.ListPeersResponse\x12U\n" +
	"\fConnectPeers\x12!.clientrpc.v1.ConnectPeersRequest\x1a\".clientrpc.v1.ConnectPeersResponse\x12U\n" +
	"\fListSessions\x12!.clientrpc.v1.ListSessionsRequest\x1a\".clientrpc.v1.ListSessionsResponse\x12R\n" +
	"\vGetNodeInfo\x12 .clientrpc.v1.GetNodeInfoRequest\x1a!.clientrpc.v1.GetNodeInfoResponse\x12N\n" +
	"\x0fSubscribeEvents\x12$.clientrpc.v1.SubscribeEventsRequest\x1a\x13.clientrpc.v1.Event0\x01B=Z;github.com/sivepanda/p2poker/internal/clientrpc/clientrpcpbb\x06proto3"

var (
	file_proto_clientrpc_v1_clientrpc_proto_rawDescOnce sync.Once
	file_proto_clientrpc_v1_clientrpc_proto_rawDescData []byte
)

func file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP() []byte {
	file_proto_clientrpc_v1_clientrpc_proto_rawDescOnce.Do(func() {
		file_proto_clientrpc_v1_clientrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_clientrpc_v1_clientrpc_proto_rawDesc), len(file_proto_clientrpc_v1_clientrpc_proto_rawDesc)))
	})
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescData
}

var file_proto_clientrpc_v1_clientrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_clientrpc_v1_clientrpc_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),   // 0: clientrpc.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),  // 1: clientrpc.v1.CreateSessionResponse
	(*JoinSessionRequest)(nil),     // 2: clientrpc.v1.JoinSessionRequest
	(*JoinSessionResponse)(nil),    // 3: clientrpc.v1.JoinSessionResponse
	(*ListPeersRequest)(nil),       // 4: clientrpc.v1.ListPeersRequest
	(*ListPeersResponse)(nil),      // 5: clientrpc.v1.ListPeersResponse
	(*PeerInfo)(nil),               // 6: clientrpc.v1.PeerInfo
	(*ConnectPeersRequest)(nil),    // 7: clientrpc.v1.ConnectPeersRequest
	(*ConnectPeersResponse)(nil),   // 8: clientrpc.v1.ConnectPeersResponse
	(*ListSessionsRequest)(nil),    // 9: clientrpc.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),   // 10: clientrpc.v1.ListSessionsResponse
	(*GetNodeInfoRequest)(nil),     // 11: clientrpc.v1.GetNodeInfoRequest
	(*GetNodeInfoResponse)(nil),    // 12: clientrpc.v1.GetNodeInfoResponse
	(*SubscribeEventsRequest)(nil), // 13: clientrpc.v1.SubscribeEventsRequest
	(*Event)(nil),                  // 14: clientrpc.v1.Event
	(*PeerMessageEvent)(nil),       // 15: clientrpc.v1.PeerMessageEvent
}
var file_proto_clientrpc_v1_clientrpc_proto_depIdxs = []int32{
	6,  // 0: clientrpc.v1.ListPeersResponse.peers:type_name -> clientrpc.v1.PeerInfo
	15, // 1: clientrpc.v1.Event.peer_message:type_name -> clientrpc.v1.PeerMessageEvent
	0,  // 2: clientrpc.v1.PokerNode.CreateSession:input_type -> clientrpc.v1.CreateSessionRequest
	2,  // 3: clientrpc.v1.PokerNode.JoinSession:input_type -> clientrpc.v1.JoinSessionRequest
	4,  // 4: clientrpc.v1.PokerNode.ListPeers:input_type -> clientrpc.v1.ListPeersRequest
	7,  // 5: clientrpc.v1.PokerNode.ConnectPeers:input_type -> clientrpc.v1.ConnectPeersRequest
	9,  // 6: clientrpc.v1.PokerNode.ListSessions:input_type -> clientrpc.v1.ListSessionsRequest
	11, // 7: clientrpc.v1.PokerNode.GetNodeInfo:input_type -> clientrpc.v1.GetNodeInfoRequest
	13, // 8: clientrpc.v1.PokerNode.SubscribeEvents:input_type -> clientrpc.v1.SubscribeEventsRequest
	1,  // 9: clientrpc.v1.PokerNode.CreateSession:output_type -> clientrpc.v1.CreateSessionResponse
	3,  // 10: clientrpc.v1.PokerNode.JoinSession:output_type -> clientrpc.v1.JoinSessionResponse
	5,  // 11: clientrpc.v1.PokerNode.ListPeers:output_type -> clientrpc.v1.ListPeersResponse
	8,  // 12: clientrpc.v1.PokerNode.ConnectPeers:output_type -> clientrpc.v1.ConnectPeersResponse
	10, // 13: clientrpc.v1.PokerNode.ListSessions:output_type -> clientrpc.v1.ListSessionsResponse
	12, // 14: clientrpc.v1.PokerNode.GetNodeInfo:output_type -> clientrpc.v1.GetNodeInfoResponse
	14, // 15: clientrpc.v1.PokerNode.SubscribeEvents:output_type -> clientrpc.v1.Event
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_clientrpc_v1_clientrpc_proto_init() }
func file_proto_clientrpc_v1_clientrpc_proto_init() {
	if File_proto_clientrpc_v1_clientrpc_proto != nil {
		return
	}
	file_proto_clientrpc_v1_clientrpc_proto_msgTypes[14].OneofWrappers = []any{
		(*Event_PeerMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_clientrpc_v1_clientrpc_proto_rawDesc), len(file_proto_clientrpc_v1_clientrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_clientrpc_v1_clientrpc_proto_goTypes,
		DependencyIndexes: file_proto_clientrpc_v1_clientrpc_proto_depIdxs,
		MessageInfos:      file_proto_clientrpc_v1_clientrpc_proto_msgTypes,
	}.Build()
	File_proto_clientrpc_v1_clientrpc_proto = out.File
	file_proto_clientrpc_v1_clientrpc_proto_goTypes = nil
	file_proto_clientrpc_v1_clientrpc_proto_depIdxs = nil
}
