// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/clientrpc/v1/clientrpc.proto

package clientrpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionKind int32

const (
	ActionKind_ACTION_KIND_FOLD  ActionKind = 0
	ActionKind_ACTION_KIND_CHECK ActionKind = 1
	ActionKind_ACTION_KIND_CALL  ActionKind = 2
	ActionKind_ACTION_KIND_RAISE ActionKind = 3
)

// Enum value maps for ActionKind.
var (
	ActionKind_name = map[int32]string{
		0: "ACTION_KIND_FOLD",
		1: "ACTION_KIND_CHECK",
		2: "ACTION_KIND_CALL",
		3: "ACTION_KIND_RAISE",
	}
	ActionKind_value = map[string]int32{
		"ACTION_KIND_FOLD":  0,
		"ACTION_KIND_CHECK": 1,
		"ACTION_KIND_CALL":  2,
		"ACTION_KIND_RAISE": 3,
	}
)

func (x ActionKind) Enum() *ActionKind {
	p := new(ActionKind)
	*p = x
	return p
}

func (x ActionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_clientrpc_v1_clientrpc_proto_enumTypes[0].Descriptor()
}

func (ActionKind) Type() protoreflect.EnumType {
	return &file_proto_clientrpc_v1_clientrpc_proto_enumTypes[0]
}

func (x ActionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionKind.Descriptor instead.
func (ActionKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{0}
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type JoinSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinSessionRequest) Reset() {
	*x = JoinSessionRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSessionRequest) ProtoMessage() {}

func (x *JoinSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSessionRequest.ProtoReflect.Descriptor instead.
func (*JoinSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{2}
}

func (x *JoinSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type JoinSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinSessionResponse) Reset() {
	*x = JoinSessionResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSessionResponse) ProtoMessage() {}

func (x *JoinSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSessionResponse.ProtoReflect.Descriptor instead.
func (*JoinSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{3}
}

func (x *JoinSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersRequest) Reset() {
	*x = ListPeersRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersRequest) ProtoMessage() {}

func (x *ListPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersRequest.ProtoReflect.Descriptor instead.
func (*ListPeersRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{4}
}

type ListPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersResponse) Reset() {
	*x = ListPeersResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersResponse) ProtoMessage() {}

func (x *ListPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersResponse.ProtoReflect.Descriptor instead.
func (*ListPeersResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{5}
}

func (x *ListPeersResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{6}
}

func (x *PeerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PeerInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type ConnectPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectPeersRequest) Reset() {
	*x = ConnectPeersRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectPeersRequest) ProtoMessage() {}

func (x *ConnectPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectPeersRequest.ProtoReflect.Descriptor instead.
func (*ConnectPeersRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{7}
}

type ConnectPeersResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConnectedCount int32                  `protobuf:"varint,1,opt,name=connected_count,json=connectedCount,proto3" json:"connected_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectPeersResponse) Reset() {
	*x = ConnectPeersResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectPeersResponse) ProtoMessage() {}

func (x *ConnectPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectPeersResponse.ProtoReflect.Descriptor instead.
func (*ConnectPeersResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{8}
}

func (x *ConnectPeersResponse) GetConnectedCount() int32 {
	if x != nil {
		return x.ConnectedCount
	}
	return 0
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{9}
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionIds    []string               `protobuf:"bytes,1,rep,name=session_ids,json=sessionIds,proto3" json:"session_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{10}
}

func (x *ListSessionsResponse) GetSessionIds() []string {
	if x != nil {
		return x.SessionIds
	}
	return nil
}

type StartGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameRequest) Reset() {
	*x = StartGameRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequest) ProtoMessage() {}

func (x *StartGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequest.ProtoReflect.Descriptor instead.
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{11}
}

type StartGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameResponse) Reset() {
	*x = StartGameResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameResponse) ProtoMessage() {}

func (x *StartGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameResponse.ProtoReflect.Descriptor instead.
func (*StartGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{12}
}

type SubmitActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ActionKind             `protobuf:"varint,1,opt,name=kind,proto3,enum=clientrpc.v1.ActionKind" json:"kind,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` // only meaningful for RAISE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitActionRequest) Reset() {
	*x = SubmitActionRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitActionRequest) ProtoMessage() {}

func (x *SubmitActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitActionRequest.ProtoReflect.Descriptor instead.
func (*SubmitActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{13}
}

func (x *SubmitActionRequest) GetKind() ActionKind {
	if x != nil {
		return x.Kind
	}
	return ActionKind_ACTION_KIND_FOLD
}

func (x *SubmitActionRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type SubmitActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitActionResponse) Reset() {
	*x = SubmitActionResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitActionResponse) ProtoMessage() {}

func (x *SubmitActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitActionResponse.ProtoReflect.Descriptor instead.
func (*SubmitActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{14}
}

type GetCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsRequest) Reset() {
	*x = GetCardsRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsRequest) ProtoMessage() {}

func (x *GetCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsRequest.ProtoReflect.Descriptor instead.
func (*GetCardsRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{15}
}

type GetCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hand          []string               `protobuf:"bytes,1,rep,name=hand,proto3" json:"hand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsResponse) Reset() {
	*x = GetCardsResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsResponse) ProtoMessage() {}

func (x *GetCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsResponse.ProtoReflect.Descriptor instead.
func (*GetCardsResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{16}
}

func (x *GetCardsResponse) GetHand() []string {
	if x != nil {
		return x.Hand
	}
	return nil
}

type GetNodeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoRequest) Reset() {
	*x = GetNodeInfoRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoRequest) ProtoMessage() {}

func (x *GetNodeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetNodeInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{17}
}

type GetNodeInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ListenAddr    string                 `protobuf:"bytes,2,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Attached      bool                   `protobuf:"varint,4,opt,name=attached,proto3" json:"attached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoResponse) Reset() {
	*x = GetNodeInfoResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoResponse) ProtoMessage() {}

func (x *GetNodeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoResponse.ProtoReflect.Descriptor instead.
func (*GetNodeInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{18}
}

func (x *GetNodeInfoResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetNodeInfoResponse) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *GetNodeInfoResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetNodeInfoResponse) GetAttached() bool {
	if x != nil {
		return x.Attached
	}
	return false
}

type AttachDispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DispatchAddr  string                 `protobuf:"bytes,1,opt,name=dispatch_addr,json=dispatchAddr,proto3" json:"dispatch_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachDispatchRequest) Reset() {
	*x = AttachDispatchRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachDispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachDispatchRequest) ProtoMessage() {}

func (x *AttachDispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachDispatchRequest.ProtoReflect.Descriptor instead.
func (*AttachDispatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{19}
}

func (x *AttachDispatchRequest) GetDispatchAddr() string {
	if x != nil {
		return x.DispatchAddr
	}
	return ""
}

type AttachDispatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachDispatchResponse) Reset() {
	*x = AttachDispatchResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachDispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachDispatchResponse) ProtoMessage() {}

func (x *AttachDispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachDispatchResponse.ProtoReflect.Descriptor instead.
func (*AttachDispatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{20}
}

func (x *AttachDispatchResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type DetachDispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachDispatchRequest) Reset() {
	*x = DetachDispatchRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachDispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachDispatchRequest) ProtoMessage() {}

func (x *DetachDispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachDispatchRequest.ProtoReflect.Descriptor instead.
func (*DetachDispatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{21}
}

type DetachDispatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachDispatchResponse) Reset() {
	*x = DetachDispatchResponse{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachDispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachDispatchResponse) ProtoMessage() {}

func (x *DetachDispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachDispatchResponse.ProtoReflect.Descriptor instead.
func (*DetachDispatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{22}
}

type SubscribeEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{23}
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*Event_PeerMessage
	Event         isEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{24}
}

func (x *Event) GetEvent() isEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Event) GetPeerMessage() *PeerMessageEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_PeerMessage); ok {
			return x.PeerMessage
		}
	}
	return nil
}

type isEvent_Event interface {
	isEvent_Event()
}

type Event_PeerMessage struct {
	PeerMessage *PeerMessageEvent `protobuf:"bytes,1,opt,name=peer_message,json=peerMessage,proto3,oneof"`
}

func (*Event_PeerMessage) isEvent_Event() {}

type PeerMessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	MessageType   string                 `protobuf:"bytes,2,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerMessageEvent) Reset() {
	*x = PeerMessageEvent{}
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMessageEvent) ProtoMessage() {}

func (x *PeerMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clientrpc_v1_clientrpc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMessageEvent.ProtoReflect.Descriptor instead.
func (*PeerMessageEvent) Descriptor() ([]byte, []int) {
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP(), []int{25}
}

func (x *PeerMessageEvent) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *PeerMessageEvent) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *PeerMessageEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_proto_clientrpc_v1_clientrpc_proto protoreflect.FileDescriptor

const file_proto_clientrpc_v1_clientrpc_proto_rawDesc = "" +
	"\n" +
	"\"proto/clientrpc/v1/clientrpc.proto\x12\fclientrpc.v1\"5\n" +
	"\x14CreateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"6\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"3\n" +
	"\x12JoinSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"4\n" +
	"\x13JoinSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x12\n" +
	"\x10ListPeersRequest\"A\n" +
	"\x11ListPeersResponse\x12,\n" +
	"\x05peers\x18\x01 \x03(\v2\x16.clientrpc.v1.PeerInfoR\x05peers\".\n" +
	"\bPeerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\"\x15\n" +
	"\x13ConnectPeersRequest\"?\n" +
	"\x14ConnectPeersResponse\x12'\n" +
	"\x0fconnected_count\x18\x01 \x01(\x05R\x0econnectedCount\"\x15\n" +
	"\x13ListSessionsRequest\"7\n" +
	"\x14ListSessionsResponse\x12\x1f\n" +
	"\vsession_ids\x18\x01 \x03(\tR\n" +
	"sessionIds\"\x12\n" +
	"\x10StartGameRequest\"\x13\n" +
	"\x11StartGameResponse\"[\n" +
	"\x13SubmitActionRequest\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.clientrpc.v1.ActionKindR\x04kind\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\"\x16\n" +
	"\x14SubmitActionResponse\"\x11\n" +
	"\x0fGetCardsRequest\"&\n" +
	"\x10GetCardsResponse\x12\x12\n" +
	"\x04hand\x18\x01 \x03(\tR\x04hand\"\x14\n" +
	"\x12GetNodeInfoRequest\"\x8a\x01\n" +
	"\x13GetNodeInfoResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vlisten_addr\x18\x02 \x01(\tR\n" +
	"listenAddr\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1a\n" +
	"\battached\x18\x04 \x01(\bR\battached\"<\n" +
	"\x15AttachDispatchRequest\x12#\n" +
	"\rdispatch_addr\x18\x01 \x01(\tR\fdispatchAddr\"1\n" +
	"\x16AttachDispatchResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\x17\n" +
	"\x15DetachDispatchRequest\"\x18\n" +
	"\x16DetachDispatchResponse\"\x18\n" +
	"\x16SubscribeEventsRequest\"U\n" +
	"\x05Event\x12C\n" +
	"\fpeer_message\x18\x01 \x01(\v2\x1e.clientrpc.v1.PeerMessageEventH\x00R\vpeerMessageB\a\n" +
	"\x05event\"c\n" +
	"\x10PeerMessageEvent\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12!\n" +
	"\fmessage_type\x18\x02 \x01(\tR\vmessageType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload*f\n" +
	"\n" +
	"ActionKind\x12\x14\n" +
	"\x10ACTION_KIND_FOLD\x10\x00\x12\x15\n" +
	"\x11ACTION_KIND_CHECK\x10\x01\x12\x14\n" +
	"\x10ACTION_KIND_CALL\x10\x02\x12\x15\n" +
	"\x11ACTION_KIND_RAISE\x10\x032\x83\b\n" +
	"\tPokerNode\x12X\n" +
	"\rCreateSession\x12\".clientrpc.v1.CreateSessionRequest\x1a#.clientrpc.v1.CreateSessionResponse\x12R\n" +
	"\vJoinSession\x12 .clientrpc.v1.JoinSessionRequest\x1a!.clientrpc.v1.JoinSessionResponse\x12L\n" +
	"\tListPeers\x12\x1e.clientrpc.v1.ListPeersRequest\x1a\x1f.clientrpc.v1.ListPeersResponse\x12U\n" +
	"\fConnectPeers\x12!.clientrpc.v1.ConnectPeersRequest\x1a\".clientrpc.v1.ConnectPeersResponse\x12U\n" +
	"\fListSessions\x12!.clientrpc.v1.ListSessionsRequest\x1a\".clientrpc.v1.ListSessionsResponse\x12L\n" +
	"\tStartGame\x12\x1e.clientrpc.v1.StartGameRequest\x1a\x1f.clientrpc.v1.StartGameResponse\x12U\n" +
	"\fSubmitAction\x12!.clientrpc.v1.SubmitActionRequest\x1a\".clientrpc.v1.SubmitActionResponse\x12I\n" +
	"\bGetCards\x12\x1d.clientrpc.v1.GetCardsRequest\x1a\x1e.clientrpc.v1.GetCardsResponse\x12R\n" +
	"\vGetNodeInfo\x12 .clientrpc.v1.GetNodeInfoRequest\x1a!.clientrpc.v1.GetNodeInfoResponse\x12[\n" +
	"\x0eAttachDispatch\x12#.clientrpc.v1.AttachDispatchRequest\x1a$.clientrpc.v1.AttachDispatchResponse\x12[\n" +
	"\x0eDetachDispatch\x12#.clientrpc.v1.DetachDispatchRequest\x1a$.clientrpc.v1.DetachDispatchResponse\x12N\n" +
	"\x0fSubscribeEvents\x12$.clientrpc.v1.SubscribeEventsRequest\x1a\x13.clientrpc.v1.Event0\x01B=Z;github.com/sivepanda/p2poker/internal/clientrpc/clientrpcpbb\x06proto3"

var (
	file_proto_clientrpc_v1_clientrpc_proto_rawDescOnce sync.Once
	file_proto_clientrpc_v1_clientrpc_proto_rawDescData []byte
)

func file_proto_clientrpc_v1_clientrpc_proto_rawDescGZIP() []byte {
	file_proto_clientrpc_v1_clientrpc_proto_rawDescOnce.Do(func() {
		file_proto_clientrpc_v1_clientrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_clientrpc_v1_clientrpc_proto_rawDesc), len(file_proto_clientrpc_v1_clientrpc_proto_rawDesc)))
	})
	return file_proto_clientrpc_v1_clientrpc_proto_rawDescData
}

var file_proto_clientrpc_v1_clientrpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_clientrpc_v1_clientrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_clientrpc_v1_clientrpc_proto_goTypes = []any{
	(ActionKind)(0),                // 0: clientrpc.v1.ActionKind
	(*CreateSessionRequest)(nil),   // 1: clientrpc.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),  // 2: clientrpc.v1.CreateSessionResponse
	(*JoinSessionRequest)(nil),     // 3: clientrpc.v1.JoinSessionRequest
	(*JoinSessionResponse)(nil),    // 4: clientrpc.v1.JoinSessionResponse
	(*ListPeersRequest)(nil),       // 5: clientrpc.v1.ListPeersRequest
	(*ListPeersResponse)(nil),      // 6: clientrpc.v1.ListPeersResponse
	(*PeerInfo)(nil),               // 7: clientrpc.v1.PeerInfo
	(*ConnectPeersRequest)(nil),    // 8: clientrpc.v1.ConnectPeersRequest
	(*ConnectPeersResponse)(nil),   // 9: clientrpc.v1.ConnectPeersResponse
	(*ListSessionsRequest)(nil),    // 10: clientrpc.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),   // 11: clientrpc.v1.ListSessionsResponse
	(*StartGameRequest)(nil),       // 12: clientrpc.v1.StartGameRequest
	(*StartGameResponse)(nil),      // 13: clientrpc.v1.StartGameResponse
	(*SubmitActionRequest)(nil),    // 14: clientrpc.v1.SubmitActionRequest
	(*SubmitActionResponse)(nil),   // 15: clientrpc.v1.SubmitActionResponse
	(*GetCardsRequest)(nil),        // 16: clientrpc.v1.GetCardsRequest
	(*GetCardsResponse)(nil),       // 17: clientrpc.v1.GetCardsResponse
	(*GetNodeInfoRequest)(nil),     // 18: clientrpc.v1.GetNodeInfoRequest
	(*GetNodeInfoResponse)(nil),    // 19: clientrpc.v1.GetNodeInfoResponse
	(*AttachDispatchRequest)(nil),  // 20: clientrpc.v1.AttachDispatchRequest
	(*AttachDispatchResponse)(nil), // 21: clientrpc.v1.AttachDispatchResponse
	(*DetachDispatchRequest)(nil),  // 22: clientrpc.v1.DetachDispatchRequest
	(*DetachDispatchResponse)(nil), // 23: clientrpc.v1.DetachDispatchResponse
	(*SubscribeEventsRequest)(nil), // 24: clientrpc.v1.SubscribeEventsRequest
	(*Event)(nil),                  // 25: clientrpc.v1.Event
	(*PeerMessageEvent)(nil),       // 26: clientrpc.v1.PeerMessageEvent
}
var file_proto_clientrpc_v1_clientrpc_proto_depIdxs = []int32{
	7,  // 0: clientrpc.v1.ListPeersResponse.peers:type_name -> clientrpc.v1.PeerInfo
	0,  // 1: clientrpc.v1.SubmitActionRequest.kind:type_name -> clientrpc.v1.ActionKind
	26, // 2: clientrpc.v1.Event.peer_message:type_name -> clientrpc.v1.PeerMessageEvent
	1,  // 3: clientrpc.v1.PokerNode.CreateSession:input_type -> clientrpc.v1.CreateSessionRequest
	3,  // 4: clientrpc.v1.PokerNode.JoinSession:input_type -> clientrpc.v1.JoinSessionRequest
	5,  // 5: clientrpc.v1.PokerNode.ListPeers:input_type -> clientrpc.v1.ListPeersRequest
	8,  // 6: clientrpc.v1.PokerNode.ConnectPeers:input_type -> clientrpc.v1.ConnectPeersRequest
	10, // 7: clientrpc.v1.PokerNode.ListSessions:input_type -> clientrpc.v1.ListSessionsRequest
	12, // 8: clientrpc.v1.PokerNode.StartGame:input_type -> clientrpc.v1.StartGameRequest
	14, // 9: clientrpc.v1.PokerNode.SubmitAction:input_type -> clientrpc.v1.SubmitActionRequest
	16, // 10: clientrpc.v1.PokerNode.GetCards:input_type -> clientrpc.v1.GetCardsRequest
	18, // 11: clientrpc.v1.PokerNode.GetNodeInfo:input_type -> clientrpc.v1.GetNodeInfoRequest
	20, // 12: clientrpc.v1.PokerNode.AttachDispatch:input_type -> clientrpc.v1.AttachDispatchRequest
	22, // 13: clientrpc.v1.PokerNode.DetachDispatch:input_type -> clientrpc.v1.DetachDispatchRequest
	24, // 14: clientrpc.v1.PokerNode.SubscribeEvents:input_type -> clientrpc.v1.SubscribeEventsRequest
	2,  // 15: clientrpc.v1.PokerNode.CreateSession:output_type -> clientrpc.v1.CreateSessionResponse
	4,  // 16: clientrpc.v1.PokerNode.JoinSession:output_type -> clientrpc.v1.JoinSessionResponse
	6,  // 17: clientrpc.v1.PokerNode.ListPeers:output_type -> clientrpc.v1.ListPeersResponse
	9,  // 18: clientrpc.v1.PokerNode.ConnectPeers:output_type -> clientrpc.v1.ConnectPeersResponse
	11, // 19: clientrpc.v1.PokerNode.ListSessions:output_type -> clientrpc.v1.ListSessionsResponse
	13, // 20: clientrpc.v1.PokerNode.StartGame:output_type -> clientrpc.v1.StartGameResponse
	15, // 21: clientrpc.v1.PokerNode.SubmitAction:output_type -> clientrpc.v1.SubmitActionResponse
	17, // 22: clientrpc.v1.PokerNode.GetCards:output_type -> clientrpc.v1.GetCardsResponse
	19, // 23: clientrpc.v1.PokerNode.GetNodeInfo:output_type -> clientrpc.v1.GetNodeInfoResponse
	21, // 24: clientrpc.v1.PokerNode.AttachDispatch:output_type -> clientrpc.v1.AttachDispatchResponse
	23, // 25: clientrpc.v1.PokerNode.DetachDispatch:output_type -> clientrpc.v1.DetachDispatchResponse
	25, // 26: clientrpc.v1.PokerNode.SubscribeEvents:output_type -> clientrpc.v1.Event
	15, // [15:27] is the sub-list for method output_type
	3,  // [3:15] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_clientrpc_v1_clientrpc_proto_init() }
func file_proto_clientrpc_v1_clientrpc_proto_init() {
	if File_proto_clientrpc_v1_clientrpc_proto != nil {
		return
	}
	file_proto_clientrpc_v1_clientrpc_proto_msgTypes[24].OneofWrappers = []any{
		(*Event_PeerMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_clientrpc_v1_clientrpc_proto_rawDesc), len(file_proto_clientrpc_v1_clientrpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_clientrpc_v1_clientrpc_proto_goTypes,
		DependencyIndexes: file_proto_clientrpc_v1_clientrpc_proto_depIdxs,
		EnumInfos:         file_proto_clientrpc_v1_clientrpc_proto_enumTypes,
		MessageInfos:      file_proto_clientrpc_v1_clientrpc_proto_msgTypes,
	}.Build()
	File_proto_clientrpc_v1_clientrpc_proto = out.File
	file_proto_clientrpc_v1_clientrpc_proto_goTypes = nil
	file_proto_clientrpc_v1_clientrpc_proto_depIdxs = nil
}
